name: Tag by git commit

on:
    workflow_dispatch:
#   push:
#     branches:
#       - main
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  tag:
    name: add tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Get current version
        id: current_version
        run: |
          version=$(git rev-list --count HEAD)
          echo "Curent version: $version"
          echo "current_version=$version" >> $GITHUB_OUTPUT
      - name: Tag and push
        run: |
          git config --global --add safe.directory /github/workspace
          git fetch --tags
          sudo apt-get install jp -y
          new_tag=${{ steps.current_version.outputs.current_version }}
          git tag "$new_tag"
          
          dt=$(date '+%Y-%m-%dT%H:%M:%SZ')
          full_name=$GITHUB_REPOSITORY
          git_refs_url=$(jq .repository.git_refs_url "$GITHUB_EVENT_PATH" | tr -d '"' | sed 's/{\/sha}//g')
          commit=$(git rev-parse HEAD)
          echo "$dt: **pushing tag $new_tag to repo $full_name"
          echo "git_refs_url: $git_refs_url"
          git_refs_response=$(
          curl -s -X POST "$git_refs_url" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d @- << EOF
          
          {
            "ref": "refs/tags/$new_tag",
            "sha": "$commit"
          }
          EOF
          )
          git_ref_posted=$( echo "${git_refs_response}" | jq .ref | tr -d '"' )
          echo $git_refs_response
          if [ "$git_ref_posted" = "refs/tags/$new_tag" ]
          then
              echo "successed."          
              exit 0
          else
              echo "::error::Tag was not created properly."
              exit 1
          fi
